language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
script:
  - ./bin/php-cs-fixer fix --dry-run
  - phpunit -c app/
before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
