language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
script:
  - ./bin/php-cs-fixer fix --dry-run -vv
  - phpunit -c app/
before_script:
  - mysql -e 'create database symfony;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - app/console doctrine:schema:update --force
